# Basic dependabot.yml file with
# https://docs.github.com/en/github/administering-a-repository/enabling-and-disabling-version-updates#example-dependabotyml-file

version: 2
updates:
  # checking for develop branch which contains v2 code of this plugin
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    reviewers:
      - "icelam"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
    rebase-strategy: "auto"
    reviewers:
      - "icelam"
